### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by jeiros** [ramnes/context-color#10]
This looks great!

A simple question: Do I need to add the
```bash
export PS1="$(context-color -p)$PS1\[\e[0m\]"
```
line to the `~/.bashrc` of every user I might be `su`'ing as?

Thanks.

**Comment by ramnes** [comment]
Hello @jeiros, thanks for the kind words!

As the README says:
> Then you could make this customization permanent by adding this line to your `~/.bashrc`, **or to the system-wide `bashrc` file (most likely somewhere in `/etc/`, depending on your distribution) if you would want all users to benefit from this.**

If you use `sudo` rather than `su`, another possibility is to add something like this to your own `~/.bashrc`:
```sh
alias sudo='sudo HOME=$HOME'
```
(`sudo -E` should work also, I guess)

Doing this will pass your `HOME` environment variable, and thus use your own `.bashrc` rather than the user's one or the default one. In my opinion, this is the best solution (and the one I use for years without any problem), because you don't change other users profiles nor system files.

So all in all, you have three possibilities:
* Modifying your system-wide `bashrc` file
* Changing all the `~/.bashrc` files
* Passing your environment along when using `sudo`

Does that answer your question?

**Comment by jeiros** [comment]
That makes a lot of sense! Thanks for the quick answer. Should've read the README more thoroughly 😄
