### ISSUE TITLE
--comand flag error

### ISSUE THREAD

**Issue by ghost** [ramnes/context-color#3]
```
$ context-color --command "date"
Illegal option --
/home/user/bin/context-color: 1: eval: ommand: not found
```
 GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
 ubuntu 17.10

**Comment by ramnes** [comment]
Hi @apnewberry,

This is because there is no such thing as a `--command` option; you meant to use `--context`.

The error message isn't very clear, partly because `getopts` doesn't support long options by default and I had to "hack" it to. While I don't plan on fixing this myself, I'd accept a PR to switch from `getopts` to whatever other standard that handles long options.

I'm going to close this, feel free to comment and or reopen another issue if needed. :+1:

**Comment by ghost** [comment]
Ah, my mistake. Thanks.
